spring.application.name=ems-backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ems}
spring.datasource.username=${DB_USERNAME:ems}
spring.datasource.password=${DB_PASSWORD:ems}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

server.port=${PORT:8080}